Add Dockerfile, add multi hotspot
konstk1/helium-dashboard pull request #9
Opened 2022-03-25 23:24 UTC by ThomDietrich

Hey,
this implements #7 and #8. I hope you don't mind they are in one PR.

2022-03-26 00:16 UTC, konstk1 requested changes

2022-03-26 00:16 UTC, konstk1 commented on src/helium.js
> +  let funcList = (process.env.HELIUM_HOTSPOT.split(",")).map(function (hotspot) {
This could use a better name.

2022-03-26 00:25 UTC, konstk1 approved these changes

2022-03-26 00:27 UTC, merged

2022-03-29 11:21 UTC, ideasman69 commented
Thanks @ThomDietrich - this is exactly what I was after 😄